# Configuración del servidor
server.port=8080

# Configuración de la base de datos PostgreSQL
# NOTA: Cambia "localhost", "5432", "postgres" y la contraseña según tu entorno local
spring.datasource.url=jdbc:postgresql://localhost:5432/productos_db
spring.datasource.username=postgres
spring.datasource.password=admin

# Configuración de JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
