# Configuración del servidor
server.port=8080

# Configuración de la base de datos PostgreSQL en Render
spring.datasource.url=jdbc:postgresql://dpg-d8mhg0jbc2fs73e04isg-a.ohio-postgres.render.com:5432/bd_tienda_de_ropa_vh2c?sslmode=require
spring.datasource.username=bd_tienda_de_ropa_vh2c_user
spring.datasource.password=SYUqUzwRPj50eLGneDzaPWoBAkWxPuqj

# Configuración de JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
